[tool.poetry]
name = "mock-data"
version = "0.1.0"
description = ""
authors = ["KauanIzidoro <cnttbussineskauan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
fastapi = {extras = ["standard"], version = "^0.114.1"}
faker = "^29.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.4"
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
taskipy = "^1.13.0"
pydantic-settings = "^2.5.2"
pydantic = "^2.9.2"
google-cloud-bigquery = "^3.25.0"
faker = "^29.0.0"

[tool.ruff]
line-length = 79
extend-exclude = ['migrations', '_pycache_']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT', 'B']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'

[tool.taskipy.tasks]
lint = 'ruff check . && ruff . --diff'
format = 'ruff check . --fix && ruff format'
run = 'python3 main.py'
fake = 'python3 fakedata.py'
create_table = 'python3 bq_table.py'
pre_test = 'task lint'
test = 'pytest -s -x --cov=app_webhook -vv'
post_test = 'coverage html'
auth = 'python3 auth.py'




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
