import random
from faker import Faker
from jsonl_convert import jsonl_data,input_num_linhas

faker = Faker('pt_BR')

def clean_value(value):
    """Remove caracteres não numéricos de um valor e retorna como inteiro."""
    return int("".join(filter(str.isdigit, value)))

def custom_secondary_address():
    options = ["Casa", "Ap.", "Bloco", "Fundos", "Loja"]
    return f"{random.choice(options)} {random.randint(1, 300)}"

def function_pfs_raw_credit(num_records):
    data = {'adesoes_pfin': [], 'adesoes_pfin_incremental':[],'exclusoes_chapa_loja_pfin': [],'faturas_pfin': [], 'garantias_seguros': [], 'motivos_cancelamentos': [], 'produtos_financeiros': [], 'tipos_canais': [], 'tipos_cancelamentos': [], 'valores_pfin': []}
    for _ in range(num_records):
        criar_adesoes_pfin = {
            'num_seq_adesao': faker.random_number(digits=10, fix_len=True),
            'cod_produto_financeiro': faker.random_number(digits=5, fix_len=True),
            'pfin_dat_ini_vigencia': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'cod_tipo_adesao': faker.random_number(digits=2, fix_len=True),
            'dat_adesao': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'dat_ini_vigencia': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'val_adesao': faker.random_number(digits=8, fix_len=True),
            'dat_ult_atu': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'nom_user_atu': faker.user_name(),
            'num_adesao': faker.random_number(digits=10, fix_len=True),
            'num_certificado': faker.bothify(text='?########'),
            'dat_fim_vigencia': faker.future_datetime().strftime('%Y-%m-%d %H:%M:%S'),
            'val_repasse': faker.random_number(digits=8, fix_len=True),
            'num_chapa_adesao': faker.random_number(digits=5, fix_len=True),
            'val_com_gerente': faker.random_number(digits=6, fix_len=True),
            'val_com_vendedor': faker.random_number(digits=6, fix_len=True),
            'qtd_parcelas': faker.random_number(digits=2, fix_len=True),
            'val_parcela': faker.random_number(digits=6, fix_len=True),
            'dat_prim_vencto': faker.future_datetime().strftime('%Y-%m-%d %H:%M:%S'),
            'dat_prim_pagto': faker.future_datetime().strftime('%Y-%m-%d %H:%M:%S'),
            'cod_documento': faker.random_number(digits=2, fix_len=True),
            'num_documento': faker.bothify(text='?########'),
            'cod_estab_adesao': faker.random_number(digits=5, fix_len=True),
            'cod_estab_venda': faker.random_number(digits=5, fix_len=True),
            'cod_estab_atrib': faker.random_number(digits=5, fix_len=True),
            'cod_tipo_cancelamento': faker.random_number(digits=2, fix_len=True),
            'dat_cancelamento': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'cod_estab_cancel': faker.random_number(digits=5, fix_len=True),
            'num_chapa_cancel': faker.random_number(digits=5, fix_len=True),
            'num_pfj_adesao': faker.random_number(digits=10, fix_len=True),
            'num_pfj_tit': faker.random_number(digits=10, fix_len=True),
            'cod_cartao': faker.random_number(digits=5, fix_len=True),
            'num_contrato': faker.random_number(digits=10, fix_len=True),
            'val_tax_financiamento': faker.random_number(digits=6, fix_len=True),
            'cod_plano_financiamento': faker.random_number(digits=5, fix_len=True),
            'tip_venda_financiada': faker.word(),
            'cod_artigo': faker.random_number(digits=5, fix_len=True),
            'cod_cor': faker.color_name(),
            'cod_tamanho': faker.word(),
            'cod_sortimento': faker.random_number(digits=5, fix_len=True),
            'val_trib_recolhido': faker.random_number(digits=8, fix_len=True),
            'val_trib_retido': faker.random_number(digits=8, fix_len=True),
            'val_devolucao': faker.random_number(digits=8, fix_len=True),
            'val_dev_perdas': faker.random_number(digits=8, fix_len=True),
            'val_dev_cliente': faker.random_number(digits=8, fix_len=True),
            'dat_dev_cliente': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'val_iof': faker.random_number(digits=6, fix_len=True),
            'val_iss': faker.random_number(digits=6, fix_len=True),
            'val_irrf': faker.random_number(digits=6, fix_len=True),
            'num_seq_movto': faker.random_number(digits=10, fix_len=True),
            'num_pdv': faker.random_number(digits=5, fix_len=True),
            'num_nsu_autorizador': faker.random_number(digits=10, fix_len=True),
            'cod_canal_venda': faker.random_number(digits=2, fix_len=True),
            'num_nota': faker.bothify(text='?########'),
            'num_serie': faker.bothify(text='?########'),
            'num_item': faker.random_number(digits=3, fix_len=True),
            'des_marca': faker.company(),
            'des_produto': faker.company(),
            'num_pedido': faker.bothify(text='?########'),
            'dat_pedido': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'dat_aprovacao_pedido': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'cod_corporacao': faker.random_number(digits=5, fix_len=True),
            'sk_contrato': faker.random_number(digits=10, fix_len=True),
            'dat_envio_admin': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'dat_envio_cancel': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'dat_nascto': faker.date_between(start_date='-70y', end_date='-18y').strftime('%Y-%m-%d %H:%M:%S'),
            'nom_cliente': faker.name(),
            'val_renda': faker.random_number(digits=8, fix_len=True),
            'sgl_sexo': faker.random_element(elements=('M', 'F')),
            'des_logradouro': faker.street_address(),
            'num_logradouro': faker.building_number(),
            'des_compl_logradouro': custom_secondary_address(),
            'cod_cep': clean_value(faker.postcode()),
            'nom_bairro': faker.street_name(),
            'nom_municipio': faker.city(),
            'sgl_estado': faker.state_abbr(),
            'cod_ddd_res': faker.random_number(digits=2, fix_len=True),
            'num_fone_res': clean_value(faker.bothify(text='########')),
            'cod_ddd_com': faker.random_number(digits=2, fix_len=True),
            'num_fone_com': clean_value(faker.bothify(text='########')),
            'cod_ddd_cel': faker.random_number(digits=2, fix_len=True),
            'num_fone_cel': clean_value(faker.bothify(text='########')),
            'des_email': faker.email(),
            'num_seq_item_envio': faker.random_number(digits=10, fix_len=True),
            'num_seq_item_receb': faker.random_number(digits=10, fix_len=True),
            'des_observacao': faker.paragraph(),
            'cod_motivo_cancel': faker.random_number(digits=2, fix_len=True),
            'num_seq_ccpf': faker.random_number(digits=10, fix_len=True),
            'cod_tipo_logradouro': faker.word(),
            'val_comissao': faker.random_number(digits=6, fix_len=True),
            'val_dev_repasse': faker.random_number(digits=8, fix_len=True),
            'num_bilhete': clean_value(faker.bothify(text='########')),
            'num_contrato_pfin': faker.random_number(digits=10, fix_len=True),
            'val_calc_cob_dano': faker.random_number(digits=8, fix_len=True),
            'val_calc_cob_roubo': faker.random_number(digits=8, fix_len=True),
            'val_calc_franquia': faker.random_number(digits=8, fix_len=True),
            'id_val_grp_fx': faker.random_number(digits=10, fix_len=True),
            'val_venda_artigo': faker.random_number(digits=8, fix_len=True),
            'val_comercial_artigo': faker.random_number(digits=8, fix_len=True),
            'tip_doc_fiscal': faker.random_number(digits=2, fix_len=True),
            'num_doc_fiscal': faker.random_number(digits=9, fix_len=True),
            'num_item_doc_fiscal': faker.random_number(digits=3, fix_len=True),
            'cod_nivel_artigo': faker.word()
        }
        data['adesoes_pfin'].append(criar_adesoes_pfin)

        criar_adesoes_pfin_incremental = {
            'num_seq_adesao': faker.random_number(digits=10, fix_len=True),
            'cod_produto_financeiro': faker.random_number(digits=5, fix_len=True),
            'pfin_dat_ini_vigencia': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'cod_tipo_adesao': faker.random_number(digits=2, fix_len=True),
            'dat_adesao': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'dat_ini_vigencia': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'val_adesao': faker.random_number(digits=8, fix_len=True),
            'dat_ult_atu': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'nom_user_atu': faker.user_name(),
            'num_adesao': faker.random_number(digits=10, fix_len=True),
            'num_certificado': faker.bothify(text='??########'),
            'dat_fim_vigencia': faker.date_time_between(start_date='now', end_date='+1y').strftime('%Y-%m-%d %H:%M:%S'),
            'val_repasse': faker.random_number(digits=8, fix_len=True),
            'num_chapa_adesao': faker.random_number(digits=5, fix_len=True),
            'val_com_gerente': faker.random_number(digits=6, fix_len=True),
            'val_com_vendedor': faker.random_number(digits=6, fix_len=True),
            'qtd_parcelas': faker.random_number(digits=2, fix_len=True),
            'val_parcela': faker.random_number(digits=6, fix_len=True),
            'dat_prim_vencto': faker.date_time_between(start_date='now', end_date='+1y').strftime('%Y-%m-%d %H:%M:%S'),
            'dat_prim_pagto': faker.date_time_between(start_date='now', end_date='+1y').strftime('%Y-%m-%d %H:%M:%S'),
            'cod_documento': faker.random_number(digits=2, fix_len=True),
            'num_documento': faker.bothify(text='??########'),
            'cod_estab_adesao': faker.random_number(digits=5, fix_len=True),
            'cod_estab_venda': faker.random_number(digits=5, fix_len=True),
            'cod_estab_atrib': faker.random_number(digits=5, fix_len=True),
            'cod_tipo_cancelamento': faker.random_number(digits=2, fix_len=True),
            'dat_cancelamento': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'cod_estab_cancel': faker.random_number(digits=5, fix_len=True),
            'num_chapa_cancel': faker.random_number(digits=5, fix_len=True),
            'num_pfj_adesao': faker.random_number(digits=10, fix_len=True),
            'num_pfj_tit': faker.random_number(digits=10, fix_len=True),
            'cod_cartao': faker.random_number(digits=10, fix_len=True),
            'num_contrato': faker.random_number(digits=10, fix_len=True),
            'val_tax_financiamento': faker.random_number(digits=6, fix_len=True),
            'cod_plano_financiamento': faker.random_number(digits=5, fix_len=True),
            'tip_venda_financiada': faker.word(),
            'cod_artigo': faker.random_number(digits=5, fix_len=True),
            'cod_cor': faker.color_name(),
            'cod_tamanho': faker.word(),
            'cod_sortimento': faker.random_number(digits=5, fix_len=True),
            'val_trib_recolhido': faker.random_number(digits=6, fix_len=True),
            'val_trib_retido': faker.random_number(digits=6, fix_len=True),
            'val_devolucao': faker.random_number(digits=6, fix_len=True),
            'val_dev_perdas': faker.random_number(digits=6, fix_len=True),
            'val_dev_cliente': faker.random_number(digits=6, fix_len=True),
            'dat_dev_cliente': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'val_iof': faker.random_number(digits=6, fix_len=True),
            'val_iss': faker.random_number(digits=6, fix_len=True),
            'val_irrf': faker.random_number(digits=6, fix_len=True),
            'num_seq_movto': faker.random_number(digits=10, fix_len=True),
            'num_pdv': faker.random_number(digits=5, fix_len=True),
            'num_nsu_autorizador': faker.random_number(digits=10, fix_len=True),
            'cod_canal_venda': faker.random_number(digits=2, fix_len=True),
            'num_nota': faker.bothify(text='??########'),
            'num_serie': faker.bothify(text='??########'),
            'num_item': faker.random_number(digits=3, fix_len=True),
            'des_marca': faker.company(),
            'des_produto': faker.word(),
            'num_pedido': faker.bothify(text='??########'),
            'dat_pedido': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'dat_aprovacao_pedido': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'cod_corporacao': faker.random_number(digits=5, fix_len=True),
            'sk_contrato': faker.random_number(digits=10, fix_len=True),
            'dat_envio_admin': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'dat_envio_cancel': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'dat_nascto': faker.date_time_between(start_date='-60y', end_date='-18y').strftime('%Y-%m-%d %H:%M:%S'),
            'nom_cliente': faker.name(),
            'val_renda': faker.random_number(digits=8, fix_len=True),
            'sgl_sexo': faker.random_element(elements=('M', 'F')),
            'des_logradouro': faker.street_address(),
            'num_logradouro': faker.building_number(),
            'des_compl_logradouro': custom_secondary_address(),
            'cod_cep': clean_value(faker.postcode()),
            'nom_bairro': faker.street_name(),
            'nom_municipio': faker.city(),
            'sgl_estado': faker.state_abbr(),
            'cod_ddd_res': faker.random_number(digits=2, fix_len=True),
            'num_fone_res': clean_value(faker.phone_number()),
            'cod_ddd_com': faker.random_number(digits=2, fix_len=True),
            'num_fone_com': clean_value(faker.phone_number()),
            'cod_ddd_cel': faker.random_number(digits=2, fix_len=True),
            'num_fone_cel': clean_value(faker.phone_number()),
            'des_email': faker.email(),
            'num_seq_item_envio': faker.random_number(digits=10, fix_len=True),
            'num_seq_item_receb': faker.random_number(digits=10, fix_len=True),
            'des_observacao': faker.paragraph(),
            'cod_motivo_cancel': faker.random_number(digits=2, fix_len=True),
            'num_seq_ccpf': faker.random_number(digits=10, fix_len=True),
            'cod_tipo_logradouro': faker.word(),
            'val_comissao': faker.random_number(digits=6, fix_len=True),
            'val_dev_repasse': faker.random_number(digits=6, fix_len=True),
            'num_bilhete': faker.bothify(text='??########'),
            'num_contrato_pfin': faker.random_number(digits=10, fix_len=True),
            'val_calc_cob_dano': faker.random_number(digits=6, fix_len=True),
            'val_calc_cob_roubo': faker.random_number(digits=6, fix_len=True),
            'val_calc_franquia': faker.random_number(digits=6, fix_len=True),
            'id_val_grp_fx': faker.random_number(digits=10, fix_len=True),
            'val_venda_artigo': faker.random_number(digits=8, fix_len=True),
            'val_comercial_artigo': faker.random_number(digits=8, fix_len=True),
            'tip_doc_fiscal': faker.random_number(digits=2, fix_len=True),
            'num_doc_fiscal': faker.random_number(digits=9, fix_len=True),
            'num_item_doc_fiscal': faker.random_number(digits=3, fix_len=True),
            'cod_nivel_artigo': faker.word()
        }
        data['adesoes_pfin_incremental'].append(criar_adesoes_pfin_incremental)
    
        criar_exclusoes_chapa_loja_pfin = {
            'COD_ESTABELECIMENTO': faker.random_number(digits=5, fix_len=True),
            'NUM_CHAPA_FUNCIONARIO': faker.random_number(digits=6, fix_len=True),
            'DAT_REFERENCIA_INI': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_REFERENCIA_FIM': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_ULT_ATU': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NOM_USER_ATU': faker.user_name()
        }
        data['exclusoes_chapa_loja_pfin'].append(criar_exclusoes_chapa_loja_pfin)

        criar_faturas_pfin = {
            'NUM_SEQ_ADESAO': faker.random_number(digits=10, fix_len=True),
            'PFIN_DAT_INI_VIGENCIA': faker.date_time_between(start_date='-5y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'COD_PRODUTO_FINANCEIRO': faker.random_number(digits=5, fix_len=True),
            'DAT_VENCTO': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'COD_TIPO_FATURA': faker.random_number(digits=2, fix_len=True),
            'NUM_FATURA': faker.random_number(digits=8, fix_len=True),
            'VAL_FATURA': faker.random_number(digits=8, fix_len=True),
            'DAT_ULT_ATU': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NOM_USER_ATU': faker.user_name(),
            'DAT_PAGTO': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'VAL_FATURA_PAGTO': faker.random_number(digits=8, fix_len=True),
            'VAL_CUSTO_EXTRATO': faker.random_number(digits=4, fix_len=True),
            'DAT_LOTE': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NUM_LOTE': faker.random_number(digits=6, fix_len=True),
            'COD_ESTAB_LOTE': faker.random_number(digits=5, fix_len=True),
            'TIPO_LOTE_RECEBIMENTO': faker.word(),
            'DAT_BONIFICACAO': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_GERACAO': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NOM_USER_GERACAO_FATURA': faker.user_name(),
            'DAT_ENVIO_ADMIN': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_ENVIO_DB_BAND': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_ENVIO_CR_BAND': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NUM_BORDERO': faker.random_number(digits=10, fix_len=True),
            'COD_GRUPO_ECONOMICO': faker.random_number(digits=5, fix_len=True),
            'TIP_NEGOCIACAO': faker.random_number(digits=2, fix_len=True),
            'DAT_ANO_MES': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NUM_BORDERO_CNC': faker.random_number(digits=10, fix_len=True),
            'COD_GRUPO_ECONOMICO_CNC': faker.random_number(digits=5, fix_len=True),
            'TIP_NEGOCIACAO_CNC': faker.random_number(digits=2, fix_len=True),
            'DAT_ANO_MES_CNC': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NUM_SEQ_ITEM_ENVIO': faker.random_number(digits=5, fix_len=True),
            'NUM_SEQ_ITEM_RECEB': faker.random_number(digits=5, fix_len=True),
            'DAT_PROCES_EXTRATO': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_BAIXA_FATURA': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'FLG_RECEBE_FATURA': faker.random_element(elements=('S', 'N')),
            'NUM_SEQ_LOTE_RECEBIMENTO': faker.random_number(digits=6, fix_len=True),
            'DAT_ENVIO_DB_ROT': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_ENVIO_CR_ROT': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'COD_PROCESSADORA': faker.random_number(digits=3, fix_len=True)
        }
        data['faturas_pfin'].append(criar_faturas_pfin)

        criar_garantias_seguros = {
            'num_pfj': faker.random_number(digits=10, fix_len=True),
            'num_documento': faker.bothify(text='###########'),
            'nom_cliente': faker.name(),
            'dat_venda_garantia': faker.date_time_between(start_date='-5y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'des_endereco': faker.street_address(),
            'des_complemento': custom_secondary_address(),
            'nom_bairro': faker.street_name(),
            'nom_municipio': faker.city(),
            'sgl_estado': faker.state_abbr(),
            'cod_cep': clean_value(faker.postcode()),
            'cod_ddd': faker.random_number(digits=2, fix_len=True),
            'num_telefone': clean_value(faker.phone_number()),
            'dat_ult_atu': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'cod_estabelecimento': faker.random_number(digits=5, fix_len=True),
            'cod_documento': faker.random_number(digits=3, fix_len=True),
            'num_garantia': faker.random_number(digits=8, fix_len=True),
            'cod_seguradora': faker.random_number(digits=3, fix_len=True),
            'cod_tipo_garantia': faker.random_number(digits=2, fix_len=True),
            'qtd_meses_garantia': faker.random_number(digits=2, fix_len=True),
            'val_garantia_venda': faker.random_number(digits=8, fix_len=True),
            'dat_garantia_fabric': faker.date_time_between(start_date='-5y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'dat_cancelamento': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'dat_movimento': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'cod_estab_cancel': faker.random_number(digits=5, fix_len=True),
            'cod_canal_venda': faker.random_number(digits=2, fix_len=True),
            'des_observacao': faker.paragraph(),
            'cod_cartao': faker.random_number(digits=10, fix_len=True),
            'cod_artigo': faker.random_number(digits=5, fix_len=True),
            'cod_cor': faker.color_name(),
            'cod_tamanho': faker.word(),
            'cod_sortimento': faker.random_number(digits=3, fix_len=True),
            'val_venda_artigo': faker.random_number(digits=8, fix_len=True),
            'des_produto': faker.word(),
            'des_marca': faker.word(),
            'num_chapa_vendedor': faker.random_number(digits=6, fix_len=True),
            'num_chapa_atu': faker.random_number(digits=6, fix_len=True)
        }
        data['garantias_seguros'].append(criar_garantias_seguros)

        criar_motivos_cancelamentos = {
            'COD_MOTIVO_CANCEL': faker.random_number(digits=3, fix_len=True),
            'DESC_MOTIVO_CANCEL': faker.sentence(),
            'COD_CANCELAMENTO': faker.random_number(digits=2, fix_len=True),
            'DAT_INI_VIGENCIA': faker.date_time_between(start_date='-5y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_FIM_VIGENCIA': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S')
        }
        data['motivos_cancelamentos'].append(criar_motivos_cancelamentos)

        criar_produtos_financeiros = {
            'COD_PRODUTO_FINANCEIRO': faker.random_number(digits=5, fix_len=True),
            'DAT_INI_VIGENCIA': faker.date_time_between(start_date='-5y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DES_PRODUTO_FINANCEIRO': faker.sentence(),
            'DAT_ULT_ATU': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NOM_USER_ATU': faker.user_name(),
            'DAT_FIM_VIGENCIA': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'COD_INTERFACE': faker.random_number(digits=2, fix_len=True),
            'IND_PRIORIDADE_PAGTO': faker.random_number(digits=1, fix_len=True),
            'COD_TIPO_PRODUTO': faker.random_number(digits=2, fix_len=True),
            'COD_ADMIN_PFIN': faker.random_number(digits=3, fix_len=True),
            'COD_ADMIN_PFIN_TERC': faker.random_number(digits=3, fix_len=True),
            'DES_PFIN_PDV': faker.sentence(),
            'DES_PFIN_EXTRATO': faker.sentence(),
            'DES_PRODUTO_FINANCEIRO_SUSEP': faker.sentence(),
            'COD_SEGURO': faker.random_number(digits=3, fix_len=True),
            'FLG_IND_DESCONTO': faker.random_element(elements=('S', 'N')),
            'SEQ_OFERTA_PDV': faker.random_number(digits=3, fix_len=True),
            'FLG_IND_GRUPO': faker.random_element(elements=('S', 'N'))
        }
        data['produtos_financeiros'].append(criar_produtos_financeiros)

        criar_tipo_canais = {
            'COD_CANAL': faker.random_number(digits=2, fix_len=True),
            'DES_CANAL': faker.job(),
            'FLG_COMMIT_AUTORIZADOR': faker.random_element(elements=('S', 'N')),
            'FLG_BANDEIRADO': faker.random_element(elements=('S', 'N'))
        }
        data['tipos_canais'].append(criar_tipo_canais)

        criar_tipos_cancelamentos = {
            'COD_CANCELAMENTO': faker.random_number(digits=2, fix_len=True),
            'DES_CANCELAMENTO': faker.sentence()
        }
        data['tipos_cancelamentos'].append(criar_tipos_cancelamentos)

        criar_valores_pfin = {
            'NUM_SEQ': faker.random_number(digits=10, fix_len=True),
            'COD_TIPO_ADESAO': faker.random_number(digits=2, fix_len=True),
            'VAL_PRODUTO': faker.random_number(digits=8, fix_len=True),
            'VAL_VENDA': faker.random_number(digits=8, fix_len=True),
            'DAT_INI_VIGENCIA': faker.date_time_between(start_date='-5y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_FIM_VIGENCIA': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'VAL_COMISSAO_ALTSA': faker.random_number(digits=6, fix_len=True),
            'VAL_REPASSE': faker.random_number(digits=6, fix_len=True),
            'VAL_PERC_COM_ALTSA': faker.random_number(digits=3, fix_len=True),
            'VAL_PERC_REPASSE': faker.random_number(digits=3, fix_len=True),
            'COD_PRODUTO_FINANCEIRO': faker.random_number(digits=5, fix_len=True),
            'PFIN_DAT_INI_VIGENCIA': faker.date_time_between(start_date='-5y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_ULT_ATU': faker.date_time_between(start_date='-1y', end_date='now').strftime('%Y-%m-%d %H:%M:%S'),
            'NOM_USER_ATU': faker.user_name(),
            'VAL_IOF_PRODUTO': faker.random_number(digits=4, fix_len=True),
            'COD_PLANO': faker.word(),
            'NUM_FAIXA': faker.random_number(digits=2, fix_len=True),
            'VAL_INI_FAIXA': faker.random_number(digits=6, fix_len=True),
            'VAL_FIM_FAIXA': faker.random_number(digits=6, fix_len=True),
            'TIP_COBERTURA_01': faker.word(),
            'QTD_DIAS_CARENCIA_01': faker.random_number(digits=3, fix_len=True),
            'QTD_DIAS_FRANQUIA_01': faker.random_number(digits=3, fix_len=True),
            'VAL_MAX_INDENIZACAO_01': faker.random_number(digits=8, fix_len=True),
            'VAL_COBERTURA_01': faker.random_number(digits=8, fix_len=True),
            'VAL_IOF_COBERTURA_01': faker.random_number(digits=4, fix_len=True),
            'TIP_COBERTURA_02': faker.word(),
            'QTD_DIAS_CARENCIA_02': faker.random_number(digits=3, fix_len=True),
            'QTD_DIAS_FRANQUIA_02': faker.random_number(digits=3, fix_len=True),
            'VAL_MAX_INDENIZACAO_02': faker.random_number(digits=8, fix_len=True),
            'VAL_COBERTURA_02': faker.random_number(digits=8, fix_len=True),
            'VAL_IOF_COBERTURA_02': faker.random_number(digits=4, fix_len=True),
            'TIP_COBERTURA_03': faker.word(),
            'QTD_DIAS_CARENCIA_03': faker.random_number(digits=3, fix_len=True),
            'QTD_DIAS_FRANQUIA_03': faker.random_number(digits=3, fix_len=True),
            'VAL_MAX_INDENIZACAO_03': faker.random_number(digits=8, fix_len=True),
            'VAL_COBERTURA_03': faker.random_number(digits=8, fix_len=True),
            'VAL_IOF_COBERTURA_03': faker.random_number(digits=4, fix_len=True),
            'TIP_COBERTURA_04': faker.word(),
            'QTD_DIAS_CARENCIA_04': faker.random_number(digits=3, fix_len=True),
            'QTD_DIAS_FRANQUIA_04': faker.random_number(digits=3, fix_len=True),
            'VAL_MAX_INDENIZACAO_04': faker.random_number(digits=8, fix_len=True),
            'VAL_COBERTURA_04': faker.random_number(digits=8, fix_len=True),
            'VAL_IOF_COBERTURA_04': faker.random_number(digits=4, fix_len=True)
        }
        data['valores_pfin'].append(criar_valores_pfin)
    jsonl_data(data=data)
    return data

num_records = input_num_linhas()
function_pfs_raw_credit(num_records)


