from faker import Faker
from datetime import datetime, date
from pydantic import BaseModel

faker = Faker('pt_BR')

def gerar_dados_adesoes_pfin(num_registros):
    dados = {}
    for _ in range(num_registros):
        registro = {
            'NUM_SEQ_ADESAO': faker.random_number(digits=10, fix_len=False),
            'COD_PRODUTO_FINANCEIRO': faker.random_number(digits=5, fix_len=False),
            'PFIN_DAT_INI_VIGENCIA': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'COD_TIPO_ADESAO': faker.random_number(digits=2, fix_len=False),
            'DAT_ADESAO': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_INI_VIGENCIA': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'VAL_ADESAO': faker.random_number(digits=8, fix_len=False),
            'DAT_ULT_ATU': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'NOM_USER_ATU': faker.user_name(),
            'NUM_ADESAO': faker.random_number(digits=10, fix_len=False),
            'NUM_CERTIFICADO': str(faker.random_number(digits=10, fix_len=True)),
            'DAT_FIM_VIGENCIA': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'VAL_REPASSE': faker.random_number(digits=8, fix_len=False),
            'NUM_CHAPA_ADESAO': faker.random_number(digits=5, fix_len=False),
            'VAL_COM_GERENTE': faker.random_number(digits=6, fix_len=False),
            'VAL_COM_VENDEDOR': faker.random_number(digits=6, fix_len=False),
            'QTD_PARCELAS': faker.random_number(digits=2, fix_len=False),
            'VAL_PARCELA': faker.random_number(digits=8, fix_len=False),
            'DAT_PRIM_VENCTO': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_PRIM_PAGTO': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'COD_DOCUMENTO': faker.random_number(digits=2, fix_len=False),
            'NUM_DOCUMENTO': faker.bothify(text='########-#'),
            'COD_ESTAB_ADESAO': faker.random_number(digits=5, fix_len=False),
            'COD_ESTAB_VENDA': faker.random_number(digits=5, fix_len=False),
            'COD_ESTAB_ATRIB': faker.random_number(digits=5, fix_len=False),
            'COD_TIPO_CANCELAMENTO': faker.random_number(digits=2, fix_len=False),
            'DAT_CANCELAMENTO': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'COD_ESTAB_CANCEL': faker.random_number(digits=5, fix_len=False),
            'NUM_CHAPA_CANCEL': faker.random_number(digits=5, fix_len=False),
            'NUM_PFJ_ADESAO': faker.random_number(digits=10, fix_len=False),
            'NUM_PFJ_TIT': faker.random_number(digits=10, fix_len=False),
            'COD_CARTAO': faker.random_number(digits=5, fix_len=False),
            'NUM_CONTRATO': faker.random_number(digits=10, fix_len=False),
            'VAL_TAX_FINANCIAMENTO': faker.random_number(digits=6, fix_len=False),
            'COD_PLANO_FINANCIAMENTO': faker.random_number(digits=5, fix_len=False),
            'TIP_VENDA_FINANCIADA': faker.word(),
            'COD_ARTIGO': faker.random_number(digits=5, fix_len=False),
            'COD_COR': faker.color_name(),
            'COD_TAMANHO': faker.word(),
            'COD_SORTIMENTO': faker.random_number(digits=5, fix_len=False),
            'VAL_TRIB_RECOLHIDO': faker.random_number(digits=8, fix_len=False),
            'VAL_TRIB_RETIDO': faker.random_number(digits=8, fix_len=False),
            'VAL_DEVOLUCAO': faker.random_number(digits=8, fix_len=False),
            'VAL_DEV_PERDAS': faker.random_number(digits=8, fix_len=False),
            'VAL_DEV_CLIENTE': faker.random_number(digits=8, fix_len=False),
            'DAT_DEV_CLIENTE': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'VAL_IOF': faker.random_number(digits=6, fix_len=False),
            'VAL_ISS': faker.random_number(digits=6, fix_len=False),
            'VAL_IRRF': faker.random_number(digits=6, fix_len=False),
            'NUM_SEQ_MOVTO': faker.random_number(digits=10, fix_len=False),
            'NUM_PDV': faker.random_number(digits=5, fix_len=False),
            'NUM_NSU_AUTORIZADOR': faker.random_number(digits=10, fix_len=False),
            'COD_CANAL_VENDA': faker.random_number(digits=2, fix_len=False),
            'NUM_NOTA': str(faker.random_number(digits=10, fix_len=True)),
            'NUM_SERIE': str(faker.random_number(digits=5, fix_len=True)),
            'NUM_ITEM': faker.random_number(digits=5, fix_len=False),
            'DES_MARCA': faker.word(),
            'DES_PRODUTO': faker.word(),
            'NUM_PEDIDO': str(faker.random_number(digits=10, fix_len=True)),
            'DAT_PEDIDO': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_APROVACAO_PEDIDO': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'COD_CORPORACAO': faker.random_number(digits=5, fix_len=False),
            'SK_CONTRATO': faker.random_number(digits=10, fix_len=False),
            'DAT_ENVIO_ADMIN': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_ENVIO_CANCEL': faker.date_time_this_year().strftime('%Y-%m-%d %H:%M:%S'),
            'DAT_NASCTO': faker.date_of_birth(minimum_age=18, maximum_age=65).strftime('%Y-%m-%d'),
            'NOM_CLIENTE': faker.name(),
            'VAL_RENDA': faker.random_number(digits=8, fix_len=False),
            'SGL_SEXO': faker.random_element(elements=['M', 'F']),
            'DES_LOGRADOURO': faker.street_address(),
            'NUM_LOGRADOURO': faker.building_number(),
            'DES_COMPL_LOGRADOURO': faker.secondary_address(),
            'COD_CEP': faker.postcode().replace('-', ''),
            'NOM_BAIRRO': faker.street_name(),
            'NOM_MUNICIPIO': faker.city(),
            'SGL_ESTADO': faker.state_abbr(),
            'COD_DDD_RES': faker.random_number(digits=2, fix_len=False),
            'NUM_FONE_RES': faker.bothify(text='########'),
            'COD_DDD_COM': faker.random_number(digits=2, fix_len=False),
            'NUM_FONE_COM': faker.bothify(text='########'),
            'COD_DDD_CEL': faker.random_number(digits=2, fix_len=False),
            'NUM_FONE_CEL': faker.bothify(text='#########'),
            'DES_EMAIL': faker.email(),
            'NUM_SEQ_ITEM_ENVIO': faker.random_number(digits=10, fix_len=False),
            'NUM_SEQ_ITEM_RECEB': faker.random_number(digits=10, fix_len=False),
            'DES_OBSERVACAO': faker.text(),
            'COD_MOTIVO_CANCEL': faker.random_number(digits=2, fix_len=False),
            'NUM_SEQ_CCPF': faker.random_number(digits=10, fix_len=False),
            'COD_TIPO_LOGRADOURO': faker.word(),
            'VAL_COMISSAO': faker.random_number(digits=6, fix_len=False),
            'VAL_DEV_REPASSE': faker.random_number(digits=8, fix_len=False),
            'NUM_BILHETE': str(faker.random_number(digits=10, fix_len=True)),
            'NUM_CONTRATO_PFIN': faker.random_number(digits=10, fix_len=False),
            'VAL_CALC_COB_DANO': faker.random_number(digits=8, fix_len=False),
            'VAL_CALC_COB_ROUBO': faker.random_number(digits=8, fix_len=False),
            'VAL_CALC_FRANQUIA': faker.random_number(digits=8, fix_len=False),
            'ID_VAL_GRP_FX': faker.random_number(digits=10, fix_len=False),
            'VAL_VENDA_ARTIGO': faker.random_number(digits=8, fix_len=False),
            'VAL_COMERCIAL_ARTIGO': faker.random_number(digits=8, fix_len=False),
            'TIP_DOC_FISCAL': faker.random_number(digits=2, fix_len=False),
            'NUM_DOC_FISCAL': str(faker.random_number(digits=10, fix_len=True)),
            'NUM_ITEM_DOC_FISCAL': faker.random_number(digits=5, fix_len=False),
            'COD_NIVEL_ARTIGO': faker.word()
        }
        dados.append(registro)
    return dados