from google.cloud import bigquery

card_schema = [
    bigquery.SchemaField("id_cartao", "STRING"),
    bigquery.SchemaField("id_produto_cartao", "STRING"),
    bigquery.SchemaField("num_cartao", "STRING"),
    bigquery.SchemaField("num_seq_via_cartao", "STRING"),
    bigquery.SchemaField("id_conta", "STRING"),
    bigquery.SchemaField("num_cpf_cliente", "STRING"),
    bigquery.SchemaField("cod_tip_portador", "STRING"),
    bigquery.SchemaField("num_bin", "STRING"),
    bigquery.SchemaField("cod_loja_emis_cartao", "STRING"),
    bigquery.SchemaField("id_cliente_so", "STRING"),
    bigquery.SchemaField("dth_emis_cartao", "TIMESTAMP"),
    bigquery.SchemaField("dth_embs_cartao", "TIMESTAMP"),
    bigquery.SchemaField("dth_valid_cartao", "TIMESTAMP"),
    bigquery.SchemaField("dth_desbloqueio", "TIMESTAMP"),
    bigquery.SchemaField("cod_sit_cartao", "STRING"),
    bigquery.SchemaField("des_sit_cartao", "STRING"),
    bigquery.SchemaField("dth_sit_cartao", "TIMESTAMP"),
    bigquery.SchemaField("cod_estagio_cartao", "STRING"),
    bigquery.SchemaField("des_estagio_cartao", "STRING"),
    bigquery.SchemaField("dth_estagio_cartao", "TIMESTAMP"),
    bigquery.SchemaField("flg_embs_loja", "STRING"),
    bigquery.SchemaField("flg_cartao_cancelado", "STRING"),
    bigquery.SchemaField("flg_cartao_provisorio", "STRING"),
    bigquery.SchemaField("flg_conta_cancelada", "STRING"),
    bigquery.SchemaField("dth_ult_atu_so", "TIMESTAMP"),
    bigquery.SchemaField("num_seq_ult_alteracao", "STRING"),
    bigquery.SchemaField("dth_inclusao_reg", "TIMESTAMP"),
    bigquery.SchemaField("pt_nomeplastico", "STRING"),
    bigquery.SchemaField("ca_arquivolote", "STRING"),
    bigquery.SchemaField("ca_id_imagem", "STRING"),
    bigquery.SchemaField("bc_responsavel", "STRING"),
    bigquery.SchemaField("ca_codigocancelamento", "STRING"),
    bigquery.SchemaField("ca_flaggeracartasenha", "STRING"),
    bigquery.SchemaField("pt_id_imagem", "STRING"),
]
