from google.cloud import bigquery

# Dataset: pfs_unificacao_cliente, Table: cliente
cliente = [
    bigquery.SchemaField('id_cliente', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('tip_pessoa', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_cpf_cnpj_cliente', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_cliente', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dth_cadastro', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_loja_cad', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_email', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dat_nascimento', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_sexo', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_loja_pref', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_ddd_cel', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_tel_cel', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_ddd_res', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_tel_res', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_lograd_end_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_endereco_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_compl_end_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_bairro_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_cidade_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_estado_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_cep_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_pais_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_ddd_com', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_tel_com', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_lograd_end_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_endereco_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_compl_end_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_bairro_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_cidade_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_estado_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_cep_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_pais_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_ddd_cob', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_tel_cob', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_lograd_end_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_endereco_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_compl_end_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_bairro_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_cidade_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_estado_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_cep_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_pais_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_ddd_ent', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_tel_ent', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_lograd_end_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_endereco_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_compl_end_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_bairro_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_cidade_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_estado_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_cep_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_pais_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_estado_civil', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('val_renda_cliente', 'NUMERIC', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_endereco_mac', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_mae_cliente', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dth_inclusao', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('dth_ult_atu_cli', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('tip_sit_telefone_res', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('tip_sit_telefone_ent', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('tip_sit_telefone_com', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('tip_sit_telefone_cob', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('tip_sit_email', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('tip_sit_telefone_cel', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('tip_origem_principal', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dat_efetivacao_crediario', 'TIMESTAMP', 'NULLABLE', description='None')
]

# Dataset: pfs_unificacao_cliente, Table: cliente_complemento
cliente_complemento = [
    bigquery.SchemaField('id_cliente', 'STRING', 'NULLABLE', description='ID do cliente.'),
    bigquery.SchemaField('tip_pessoa', 'STRING', 'NULLABLE', description='Tipo de pessoa (Física ou Jurídica).'),
    bigquery.SchemaField('num_cpf_cnpj_cliente', 'INTEGER', 'NULLABLE', description='CPF ou CNPJ do cliente.'),
    bigquery.SchemaField('cod_nacionalidade', 'INTEGER', 'NULLABLE', description='Código da nacionalidade do cliente.'),
    bigquery.SchemaField('des_nacionalidade', 'STRING', 'NULLABLE', description='Descrição da nacionalidade do cliente.'),
    bigquery.SchemaField('des_naturalidade_cidade', 'STRING', 'NULLABLE', description='Cidade de naturalidade do cliente.'),
    bigquery.SchemaField('cod_naturalidade_estado', 'STRING', 'NULLABLE', description='Código do estado de naturalidade do cliente.'),
    bigquery.SchemaField('flg_pessoa_politicamente_exposta', 'STRING', 'NULLABLE', description='Indicador se o cliente é pessoa politicamente exposta (S/N).'),
    bigquery.SchemaField('flg_deficiente_visual', 'STRING', 'NULLABLE', description='Indicador se o cliente é deficiente visual (S/N).'),
    bigquery.SchemaField('val_outra_renda_cliente', 'FLOAT', 'NULLABLE', description='Valor de outras rendas do cliente.'),
    bigquery.SchemaField('nom_pai_cliente', 'STRING', 'NULLABLE', description='Nome do pai do cliente.'),
    bigquery.SchemaField('num_rg', 'STRING', 'NULLABLE', description='Número do RG do cliente.'),
    bigquery.SchemaField('dat_emissao_rg', 'DATE', 'NULLABLE', description='Data de emissão do RG.'),
    bigquery.SchemaField('cod_orgao_expedicao_rg', 'STRING', 'NULLABLE', description='Código do órgão expedidor do RG.'),
    bigquery.SchemaField('cod_estado_emissao_rg', 'STRING', 'NULLABLE', description='Código do estado de emissão do RG.'),
    bigquery.SchemaField('num_cnh', 'STRING', 'NULLABLE', description='Número da CNH do cliente.'),
    bigquery.SchemaField('dat_validade_cnh', 'DATE', 'NULLABLE', description='Data de validade da CNH.'),
    bigquery.SchemaField('num_seguranca_cnh', 'STRING', 'NULLABLE', description='Número de segurança da CNH.'),
    bigquery.SchemaField('cod_validacao_cnh', 'STRING', 'NULLABLE', description='Código de validação da CNH.'),
    bigquery.SchemaField('dat_emissao_cnh', 'DATE', 'NULLABLE', description='Data de emissão da CNH.'),
    bigquery.SchemaField('val_patrimonio_total', 'FLOAT', 'NULLABLE', description='Valor total do patrimônio do cliente.'),
    bigquery.SchemaField('cod_profissao', 'INTEGER', 'NULLABLE', description='Código da profissão do cliente.'),
    bigquery.SchemaField('nom_profissao', 'STRING', 'NULLABLE', description='Nome da profissão do cliente.'),
    bigquery.SchemaField('tip_origem_principal', 'STRING', 'NULLABLE', description='Tipo de origem principal do cliente.'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE', description='Data e hora da última atualização no sistema.'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE', description='Data e hora de inclusão do registro.'),
    bigquery.SchemaField('cod_nacionalidade_iso', 'STRING', 'NULLABLE', description='Código ISO da nacionalidade.'),
    bigquery.SchemaField('des_nacionalidade_iso', 'STRING', 'NULLABLE', description='Descrição da nacionalidade (ISO).'),
    bigquery.SchemaField('cod_profissao_isco08', 'INTEGER', 'NULLABLE', description='Código da profissão (ISCO-08).'),
    bigquery.SchemaField('nom_profissao_isco08', 'STRING', 'NULLABLE', description='Nome da profissão (ISCO-08).')
]

# Dataset: pfs_unificacao_cliente, Table: cliente_item_perfil
cliente_item_perfil = [
    bigquery.SchemaField('id_cliente', 'STRING', 'NULLABLE', description='ID do cliente.'),
    bigquery.SchemaField('dth_primeiro_evento', 'TIMESTAMP', 'NULLABLE', description='Data e hora do primeiro evento.'),
    bigquery.SchemaField('dth_ultimo_evento', 'TIMESTAMP', 'NULLABLE', description='Data e hora do último evento.'),
    bigquery.SchemaField('dth_ult_atu_cli', 'TIMESTAMP', 'NULLABLE', description='Data e hora da última atualização do cliente.'),
    bigquery.SchemaField('dth_inclusao', 'TIMESTAMP', 'NULLABLE', description='Data e hora de inclusão do registro.'),
    bigquery.SchemaField('tip_origem', 'STRING', 'NULLABLE', description='Tipo de origem.'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE', description='ID do cliente no sistema.'),
    bigquery.SchemaField('flg_evento', 'STRING', 'NULLABLE', description='Flag do evento.'),
    bigquery.SchemaField('des_evento', 'STRING', 'NULLABLE', description='Descrição do evento.'),
    bigquery.SchemaField('qtd_evento', 'STRING', 'NULLABLE', description='Quantidade do evento.'),
    bigquery.SchemaField('val_evento', 'STRING', 'NULLABLE', description='Valor do evento.'),
    bigquery.SchemaField('cod_item_perfil', 'INTEGER', 'NULLABLE', description='Código do item do perfil.')
]

# Dataset: pfs_unificacao_cliente, Table: de_para_num_pfj_id_cdt_cpf
de_para_num_pfj_id_cdt_cpf = [
    bigquery.SchemaField('num_pfj', 'INTEGER', 'NULLABLE', description='Número de pessoa física ou jurídica.'),
    bigquery.SchemaField('num_cpf', 'INTEGER', 'NULLABLE', description='Número do CPF.'),
    bigquery.SchemaField('id_pessoa_cdt', 'INTEGER', 'NULLABLE', description='ID da pessoa no CDT.'),
    bigquery.SchemaField('tip_origem_cdt', 'STRING', 'NULLABLE', description='Tipo de origem do CDT.')
]

# Dataset: pfs_unificacao_cliente, Table: v_estabelecimento
v_estabelecimento = [
    bigquery.SchemaField('cod_estabelecimento', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_cgc', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_digto_estabelecimento', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('flg_ind_atividade', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('flg_localizacao', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('flg_tipo_estabelecimento', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_estabelecimento', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('flg_responsavel_mr', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dat_ult_atu', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('est_sgl_estado', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dat_fechamento', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('dat_ult_reforma', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_fantasia', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_gerente_adm', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_gerente_comercial', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dat_abertura', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_inscricao_estadual', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('num_inscricao_municipal', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('dat_inauguracao', 'TIMESTAMP', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_fantasia_mkt', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_corporacao', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_razao_social', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_regional', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_regional', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('nom_gerente', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_micro_regiao', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('des_micro_regiao', 'STRING', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_estabelecimento_cdt', 'INTEGER', 'NULLABLE', description='None'),
    bigquery.SchemaField('cod_estabelecimento_onefpay', 'INTEGER', 'NULLABLE', description='None')
]
