from google.cloud import bigquery

# Dataset: pfs_pfin_raw_dw, Table: dim_locais
dim_locais = [
    bigquery.SchemaField('sk_local', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_estabelecimento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_estabelecimento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_micro_regiao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_micro_regiao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_regional', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_regional', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_seg_geo_economico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_seg_geo_economico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_corporacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_corporacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_logradouro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_logradouro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_cep', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_bairro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_municipio', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_municipio', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_estado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_pais', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_pais', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_atividade_economica', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_atividade_economica', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_grupo_margem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_grupo_margem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_fantasia', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_abertura', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_ult_reforma', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_fechamento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_natureza', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_propriedade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_clima', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_apoio', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_situacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_operacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tamanho', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_habitantes_proximidade', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_habitantes_municipio', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('hor_abertura_semana', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('hor_fechamento_semana', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_horas_semana', 'NUMERIC', 'NULLABLE'),
    bigquery.SchemaField('hor_abertura_sabado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('hor_fechamento_sabado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_horas_sabado', 'NUMERIC', 'NULLABLE'),
    bigquery.SchemaField('hor_abertura_domingo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('hor_fechamento_domingo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_horas_domingo', 'NUMERIC', 'NULLABLE'),
    bigquery.SchemaField('val_renda_per_capita', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('qtd_metragem_quadrada_av', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_gerente_comercial', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_gerente_regional', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ind_entrega_armazem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ind_abertura_domingo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ind_responsavel_regional', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ind_responsavel_micro_regiao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ind_sk_atual', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('sk_micro_regiao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('sk_regional', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('sk_corporacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('sk_seg_geo_economico', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('sk_pais', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('sk_estado', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('sk_municipio', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('sk_clima', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_clima_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_inc_dw', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_exc_dw', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('sk_estrutura_estoque_local', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dat_inauguracao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('sk_tipo_porte_local', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cgc', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_digito_local', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_inscricao_estadual', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_inscricao_municipal', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_latitude', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_longitude', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('sk_ger_geral_venda', 'INTEGER', 'NULLABLE')
]

# Dataset: pfs_pfin_raw_dw, Table: dw_funcionario
dw_funcionario = [
    bigquery.SchemaField('sk_funcionario', 'INTEGER', 'NULLABLE', description='Chave Surrogate do funcionário'),
    bigquery.SchemaField('num_chapa_so', 'INTEGER', 'NULLABLE', description='Número da chapa do funcionário'),
    bigquery.SchemaField('nom_funcionario', 'STRING', 'NULLABLE', description='Nome do funcionário'),
    bigquery.SchemaField('sk_local', 'INTEGER', 'NULLABLE', description='Chave Surrogate do local de trabalho'),
    bigquery.SchemaField('sk_cargo', 'INTEGER', 'NULLABLE', description='Chave Surrogate do cargo do funcionário'),
    bigquery.SchemaField('dat_dia_admissao', 'TIMESTAMP', 'NULLABLE', description='Data de admissão do funcionário'),
    bigquery.SchemaField('dat_dia_demissao', 'TIMESTAMP', 'NULLABLE', description='Data de demissão do funcionário'),
    bigquery.SchemaField('dat_dia_ini_afastamento', 'TIMESTAMP', 'NULLABLE', description='Data de início do afastamento'),
    bigquery.SchemaField('dat_dia_fim_afastamento', 'TIMESTAMP', 'NULLABLE', description='Data de fim do afastamento'),
    bigquery.SchemaField('des_email', 'STRING', 'NULLABLE', description='Endereço de e-mail do funcionário'),
    bigquery.SchemaField('dat_inc_dw', 'TIMESTAMP', 'NULLABLE', description='Data de inclusão no Data Warehouse'),
    bigquery.SchemaField('dat_ult_alt_dw', 'TIMESTAMP', 'NULLABLE', description='Data da última atualização no Data Warehouse'),
    bigquery.SchemaField('dat_exc_dw', 'TIMESTAMP', 'NULLABLE', description='Data de excecução no Data Warehouse'),
    bigquery.SchemaField('sk_situacao_funcionario', 'INTEGER', 'NULLABLE', description='Chave Surrogate da situação do funcionário'),
    bigquery.SchemaField('num_cpf', 'STRING', 'NULLABLE', description='Número do CPF do funcionário'),
    bigquery.SchemaField('num_rg', 'STRING', 'NULLABLE', description='Número do RG do funcionário')
]