from google.cloud import bigquery

# Dataset: pfs_unificacao_pefisa, Table: adesao_deb_automatico
adesao_deb_automatico_schema = [
    bigquery.SchemaField('id_adesao_deb_automatico', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_data_adesao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_conta_digital', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_tipo_deb_automatico', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_tipo_deb_automatico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_user_adesao_deb_automatico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_canc_deb_automatico', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nom_user_canc_deb_automatico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_ads_deb_autm', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: adesao_pacote_tarifa_hist
adesao_pacote_tarifa_hist_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_pacote_tarifa', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_pacote_tarifa', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_tarifa', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_ativacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_desativacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_fim_ciclo', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_adesao_conta_ccred', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_ads_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: agpr_transacao_txn
agpr_transacao_txn_schema = [
    bigquery.SchemaField('cod_tipo_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_agrupamento_txn', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_agrupamento_txn', 'STRING', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: ajuste_debito
ajuste_debito_schema = [
    bigquery.SchemaField('id_conta_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_ajuste_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_ajuste_debito', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_origem_ajuste_debito', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_val_ajuste_debito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_ajuste_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_ajuste_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_ajuste_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_ajuste_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_ajuste_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_user', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_estabelecimento_externo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_multiplo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_multiplo_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_ajuste_debito', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: autorizacao_cartao_credito
autorizacao_cartao_credito_schema = [
    bigquery.SchemaField('id_autorizacao_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_autoriz_ccred', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_funcao_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cartao_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estab_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_estab_autoriz_ccred_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_estab_exter_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_canal_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_canal_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_trans_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_proc_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_tip_terminal_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_terminal_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_band_modo_entrada', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_modo_entrada_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_modo_entrada_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_autorizacao_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtd_parcela_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_terml_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_resp_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_status_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_categoria_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_motivo_neg_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_motivo_neg_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_autorizacao_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_autorizacao_ccred_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_nsuhost_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_estab_mcc_autoriz', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_estab_mcc_autoriz', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_moeda_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_moeda_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_autoriz_ons', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_instituicao_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_adquirente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_uuid', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_autorizador_antigo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_resp_autorizador_antigo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_autoriz_ccred', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: autorizacao_cartao_credito_hist
autorizacao_cartao_credito_hist_schema = [
    bigquery.SchemaField('id_autorizacao_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_autoriz_ccred', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_funcao_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cartao_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estab_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_estab_autoriz_ccred_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_estab_exter_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_canal_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_canal_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_trans_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_proc_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_tip_terminal_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_terminal_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_band_modo_entrada', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_modo_entrada_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_modo_entrada_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_autorizacao_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtd_parcela_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_terml_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_resp_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_status_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_categoria_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_motivo_neg_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_motivo_neg_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_autorizacao_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_autorizacao_ccred_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_nsuhost_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_estab_mcc_autoriz', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_estab_mcc_autoriz', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_moeda_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_moeda_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_autoriz_ons', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_instituicao_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_adquirente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_uuid', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_autorizador_antigo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_resp_autorizador_antigo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_autoriz_ccred', 'INTEGER', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: autorizacao_detalhes
autorizacao_detalhes_schema = [
    bigquery.SchemaField('id_aut_detalhe_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_uuid', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estab_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_razao_social', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_estab_exter_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estab', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_estab_cdt', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_autoriz_ons', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_score_conductor', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_score_bandeira', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_score_regra', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_aut_detalhe_1', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_aut_detalhe_2', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_aut_detalhe_3', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_cidade_evento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_pais_evento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_cep_evento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_token_evento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_token_evento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_evento_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_com_eletronico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: cadastro_chave_pix
cadastro_chave_pix_schema = [
    bigquery.SchemaField('num_cpf_cnpj_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_cad_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_chave_pix', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_chave_pix', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_chave_pix', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_chave_pix', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_chave_pix', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_status_chave_pix', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nome_cliente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_ano_mes_status', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: cartao
cartao_schema = [
    bigquery.SchemaField('id_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_via_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_modo_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_atual', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_portador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_bin', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_emis_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_emis_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_embs_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_valid_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_desbloqueio', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_agrp_sit_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_agrp_sit_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estagio_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_estagio_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_estagio_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('flg_embs_loja', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_cancelado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_provisorio', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_debito_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('pt_nomeplastico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ca_arquivolote', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ca_id_imagem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('bc_responsavel', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ca_codigocancelamento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ca_flaggeracartasenha', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('pt_id_imagem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_migrado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_cartao_migrado', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_emis_cartao', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: cartao_debito
cartao_debito_schema = [
    bigquery.SchemaField('id_conta_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_emissao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_embossing', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_validade', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_cartao_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_cartao_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_cartao_debito', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_estagio', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_stagio', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_status_allow_approve', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_portador', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_bin', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_bandeira', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_hash_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('qtd_pasword_incorreta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_temporario', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_cliente_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_multiplo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_multiplo_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_emiss_cartao_debito', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: conta
conta_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('tip_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_ads_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_canal_ads_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_politica', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_mod_score', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_score_aprov_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_operacao_proposta_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_proposta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_colab_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_chapa_colab_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_origem_entrada_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_ori_comercial', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ads_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_ads_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_ads_cred', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_ativacao_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nm_user_ativacao_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_agrp_sit_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_agrp_sit_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_financeiro_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_financeiro_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_overall_status_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_overall_status_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_overall_reason_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_overall_reason_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_dia_vencto_fatura', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_alt_vencto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_bloqueada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao_ant', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_grade_produto_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_conta_debito', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_agrp_sit_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_agrp_sit_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_financeiro_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_financeiro_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_overall_status_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_overall_status_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_overall_reason_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_overall_reason_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_banco', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_agencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dv_agencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dv_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_debito_bloqueada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_debito_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_adesao_prod_flex', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_cancel_adesao_prod_flex', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_ads_prod_flex', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_adesao_prod_flex', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_cancelamento_prod_flex', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_adesao_carteira_digital_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dt_adesao_carteira_digital', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dt_cancelamento_carteira_digital', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_adesao_carteira_digital', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_cancelamento_carteira_digital', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_overlimit_disp', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_indicacao_amigo_revendedor', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_revendedor', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_indicador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_migrada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_migracao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_ads_conta', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: conta_debito
conta_debito_schema = [
    bigquery.SchemaField('id_conta_multiplo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ads_conta_debito', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_sit_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dv_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_banco', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_agencia_conta_corrente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dv_agencia_conta_corrente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_dia_vencimento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_multiplo_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_saldo_apartado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_pacote_tarifa_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_pacote_tarifa_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_pacote_tarifa_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_endereco_entrega', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_ads_conta_debito', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: conta_hist
conta_hist_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('tip_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_ads_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_canal_ads_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_politica', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_mod_score', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_score_aprov_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_operacao_proposta_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_proposta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_colab_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_chapa_colab_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_origem_entrada_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_ori_comercial', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ads_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_ads_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_ads_cred', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_dia_vencto_fatura', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_alt_vencto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_bloqueada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao_ant', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_grade_produto_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_banco', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_agencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dv_agencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dv_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_adesao_prod_flex', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_cancel_adesao_prod_flex', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_adesao_carteira_digital_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dt_adesao_carteira_digital', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dt_cancelamento_carteira_digital', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_adesao_carteira_digital', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_cancelamento_carteira_digital', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_overlimit_disp', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_indicacao_amigo_revendedor', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_revendedor', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_indicador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_ads_conta', 'INTEGER', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: contestacoes
contestacoes_schema = [
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_virtual', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_emis_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('data_transacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_trans', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_financiado', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_operacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('data_contestacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('status_contestacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('razaocb', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cc_id_compracontestada', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dataenviocb', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('motivo2reapresentacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('trc_tiporesolucaocontestacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cc_historico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cc_parcelapedida', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dataalteracao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('tipo_contestacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('modo_entrada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_modo_entrada_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('mcc', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('reference_number', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('bandeira', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('uuid', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_score_conductor', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_score_bandeira', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('modalidade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_estab', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_evento_compra_saque', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_eventocompra', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_autorizacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_autorizacao_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('safra_trans', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('anomesdia_trans', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('anomesdia_contest', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('safra_alt', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('anomesdia_alt', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('safra_contest', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: contrato_emprestimo
contrato_emprestimo_schema = [
    bigquery.SchemaField('id_contrato_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_contrato_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_solicitacao_emprestimo', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_status_contrato', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_alteracao_status', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_vencto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_vencto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_efetivacao_emprestimo', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_credito_cliente', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_geracao_contrato_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nom_financeira', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_proposta_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_ip_assinatura', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_assinatura', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_browser_assinatura', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('per_taxa_permanencia', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_juros_nominal', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_taxa_interna_retorno', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_taxa_custo_efetivo_mes', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_taxa_iof', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_taxa_iof_complementar', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_taxa_multa', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtde_dia_cobranca_multa', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_liberado_cliente', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_financiado', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_devedor', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_depositado_cliente', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_iof', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_tarifa', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_juro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_recebivel', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_seguro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_parcela', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtde_parcela', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_modalidade_contrato', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_banco_pagto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_banco_pagto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_agencia_pagto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_dv_agencia_pagto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_conta_pagto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_class_conta_pagto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_conta_pagto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_dv_conta_pagto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_responsavel_pagto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_titular_pagto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_cliente_desde_bco_pagto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem_contrato', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_canal_emprestimo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_operador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_chapa_operador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_operador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_chapa_usuario_logado', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('qtde_parcela_atraso', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('qtde_parcela_pendente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('qtde_parcela_paga', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_multiplo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem_informacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_ano_mes_sol_empr', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: estabelecimento_externo
estabelecimento_externo_schema = [
    bigquery.SchemaField('id_estabelecimento_externo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_estabelecimento_externo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: evento_ajuste
evento_ajuste_schema = [
    bigquery.SchemaField('id_evento_ajuste', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_movimento_ajuste', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_tipo_ajuste', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_ajuste', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ajuste', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_ajuste', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_origem', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_movimento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_seq_via_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_funcao_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_vencimento_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_vencimento_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_estabelecimento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_original', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_status', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_categoria_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_responsavel_inclusao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_processamento_lojista', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_borderaux', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_processamento_lojista_dois', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_evento_externo_original', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('tip_evento_externo_original', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_lojista', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_estabelecimento_visa', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_destino', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('id_incoming', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_parcela_pedida_incoming', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_origem_resolucao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_debito_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_estabelecimento_externo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: evento_compra_saque
evento_compra_saque_schema = [
    bigquery.SchemaField('id_evento_compra_saque', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_credito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_funcao_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cartao_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_cartao_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_operacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_operacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_estab_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_estab', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_trans_ofs', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_categoria_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_trans', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_trans', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtd_parcela', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_parcela', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('cod_moeda', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_moeda', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('per_taxa_juro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_trans_origem', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_trans_destino', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('cod_moeda_dest', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_moeda_dest', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_ori_resolucao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_ori_resolucao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_estab_exter', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_estab_exter', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_estab_mcc', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_estab_mcc', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_vencto_prim_par_ep', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_estimada_vencto_ult_par_ep', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_autorizacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_tac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_iof', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_juro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_financiado', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_taxa', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_vencimento_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_origem_informacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_evento_original', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_uuid', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_reference_number', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sistema_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_compra_saque', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: evento_pagamento
evento_pagamento_schema = [
    bigquery.SchemaField('id_evento_pagamento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_credito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_funcao_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cartao_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_cartao_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_operacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_operacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_estab_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_estab', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_status', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_categoria_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_pagamento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_pago', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('cod_moeda', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_moeda', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_ori_resolucao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_ori_resolucao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_estab_exter', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_estab_exter', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_estab_mcc', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_estab_mcc', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_banco', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_vencto_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_vencto_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_autorizacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_evento_original', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_fatura_paga', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sistema_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_pagamento', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: fatura_ccred
fatura_ccred_schema = [
    bigquery.SchemaField('id_fatura_hist', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_pessoa_cdt_tit_cta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_tit_cta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dat_vencto_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_vencto_real_ant', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_vencto_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_vencto_padrao_ant', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ini_periodo_faturado', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_fim_periodo_faturado', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_documento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_situacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_situacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_ciclo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_anterior_final', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_atual_final', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_extrato_anterior', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_min_extrato_ant', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_min_extrato', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_base_multa_cobrada', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_multa_extrato', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_multa', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_multa', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_encargo_financiamento', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_encargo_atraso', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_pagamento', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_pagamento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_vencto_cobranca', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_fechto_prox_fatura', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_parcelado_futuro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_credito_pagto_minimo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_correcao_credito_minimo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtd_vencimento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('qtd_portador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_atualizacao_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_canal_envio', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_canal_envio', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_compra_nacional', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_compra_internacional', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_saque_nacional', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_saque_internacional', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_tarifa_nacional', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_seguro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_encargo_pagto_min', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_encargo_rot_periodo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_encargo_rot_prox_periodo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_parcelado_periodo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_parcelado_prox_periodo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_encargo_saque_periodo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_encargo_saque_prox_peri', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_cotacao_dolar', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_emite_extrato', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_vencto_fatura', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: grade_produto
grade_produto_schema = [
    bigquery.SchemaField('id_grade_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_cartao_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_origem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_destino', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_estabelecimento_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_estabelecimento_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_chapa_colaborador_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_colaborador_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_grade_produto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_grade_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_solicitacao_grade_produto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_migracao_grade_produto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_limite_anterior_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_novo_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_origem_web_service', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_responsavel', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_grade_automatico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_mig_grade', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: grade_produto_hist
grade_produto_hist_schema = [
    bigquery.SchemaField('id_grade_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_cartao_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_origem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_destino', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_estabelecimento_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_estabelecimento_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_chapa_colaborador_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_colaborador_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_grade_produto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_grade_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_solicitacao_grade_produto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_migracao_grade_produto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_limite_anterior_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_novo_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_origem_web_service', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_responsavel', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_grade_automatico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_mig_grade', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: limite_disponibilidade
limite_disponibilidade_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_portador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_limite_saque_nac_global', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_global_credito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_saque_nac_global', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_parcela_nac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_global_credito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_parcelas_nac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_maximo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_posicao_limite', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: limite_disponibilidade_hist
limite_disponibilidade_hist_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_portador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_limite_saque_nac_global', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_global_credito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_saque_nac_global', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_parcela_nac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_global_credito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_parcelas_nac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_maximo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_posicao_limite', 'DATE', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: meta_dia_pfin
meta_dia_pfin_schema = [
    bigquery.SchemaField('dat_dia', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_estabelecimento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_produto_financeiro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('qtd_prev_venda', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtd_real_venda', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_prev_venda', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_real_venda', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtd_prev_receb', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtd_real_receb', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_prev_receb', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_real_receb', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_prev_receb', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_real_receb', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_real_receb_acm', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: parcelamento_fatura_ccred
parcelamento_fatura_ccred_schema = [
    bigquery.SchemaField('id_parcelamento_fatura', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_vencimento_fatura', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_efetivacao_adesao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_regra_campanha', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_regra_campanha', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_adesao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_adesao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_servico_tipo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_servico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_total_parcelamento', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_atual_fatura', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_geracao_parcelamento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('qtd_parcela', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_parcela', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_taxa_refinanciamento', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_custo_efetivo_total', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_iof', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_tac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_total_refinanciamento', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_fatura_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_evento_compra', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_entrada_parcelamento', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_com_entrada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_geracao_parcel', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: produto_cartao
produto_cartao_schema = [
    bigquery.SchemaField('nom_processadora', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_parceiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_produto_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_band_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_band_produto_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_bin', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: produto_financeiro
produto_financeiro_schema = [
    bigquery.SchemaField('id_produto_financeiro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_produto_financeiro_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_produto_financeiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_produto_financeiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_seguro_mensal', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('qtd_parcelas_bonificacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_bonificacao_mensal', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_bonificacao_mensal', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: refinanciamento_fatura_ccred
refinanciamento_fatura_ccred_schema = [
    bigquery.SchemaField('id_refinanciamento_fatura', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_evento_compra', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_operacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_operacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_refinanciamento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_rotativo_paga_juro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_debito_faturado_prox', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_total_pos_prox', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_total_refinanciado', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtde_parcela', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_parcela', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_taxa_juro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_iof', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('per_cet', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('nm_responsavel', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cd_status', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_antecipacao_pendente', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_parcela_futura', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_abatimento_juro', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_saldo_total', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_total_refinanciar', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('cd_status_cashback', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_cashback', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('per_cashback', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_cashback', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('id_parcelamento_fatura', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_fatura', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_vencimento_fatura', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_refinanciamento', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: saldo_conta
saldo_conta_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_atual_final', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_saldo', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_posicao_saldo', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: saldo_conta_debito
saldo_conta_debito_schema = [
    bigquery.SchemaField('id_conta_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_conta_debito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('id_conta_multiplo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_saldo_apartado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_pos_saldo_debito', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: saldo_conta_hist
saldo_conta_hist_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_atual_final', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_saldo', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_posicao_saldo', 'DATE', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: seguradora
seguradora_schema = [
    bigquery.SchemaField('id_seguradora', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_seguradora', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cnpj_seguradora', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_seguradora_origem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_seguradora_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem_sgrd', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: seguro_adesao
seguro_adesao_schema = [
    bigquery.SchemaField('id_adesao_seguro_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_adesao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_produto_financeiro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_produto_financeiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem_pfin', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_adesao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_adesao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_canal_venda', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_canal_venda', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_canal_venda', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_canal_venda', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estabelecimento_adesao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_estabelecimento_cancel', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_situacao_seguro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_situacao_seguro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_situacao_seguro', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_cancelamento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_cancelamento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_motivo_cancelamento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_motivo_cancelamento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_cancelamento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_titularidade', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_titularidade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_seguradora', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_seguradora', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem_sgrd', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_inicio_vigencia_seguro', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_termino_vigencia_seguro', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_meses_vigencia_seguro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_premio_total', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_chapa_adesao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_chapa_cancel', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_artigo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_cor', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tamanho', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_sortimento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_artigo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sku_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_venda_artigo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('num_apolice_seguro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_adesao', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: seguro_adesao_item
seguro_adesao_item_schema = [
    bigquery.SchemaField('id_adesao_seguro_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_adesao_seguro_item_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_adesao_seguro_item', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_produto_financeiro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_produto_financeiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_adesao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente_adesao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_pessoa_adesao_item', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_adesao_item', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_item_seguro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ini_vigencia', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_fim_vigencia', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('flg_titular', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_apenas_resp_financeiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('tp_status_integracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_exclusao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_adesao_item', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: seguro_dependente
seguro_dependente_schema = [
    bigquery.SchemaField('id_pessoa_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cnpj', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('tip_pessoa', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sexo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_sexo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nm_dependente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_nascimento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nom_mae', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estado_civil', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_estado_civil', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_grau_parentesco', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_grau_parentesco', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_rg', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_uf_rg', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_emissao_rg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_pis', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cns', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_doc_nascido_vivo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_apenas_resp_financeiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_lograd_end', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_lograd_end', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_compl_end', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_bairro_end', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_municipio_end', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estado_end', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_cep_end', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dt_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: seguro_parcela
seguro_parcela_schema = [
    bigquery.SchemaField('id_adesao_seguro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_financeiro', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_produto_financeiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem_pfin', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_parcela', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_parcela', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_vencimento_parcela', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_situacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_situacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_situacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_emissao_parcela', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_cancelamento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_motivo_cancelamento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_situacao_cobranca', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_situacao_cobranca', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_situacao_transferencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_situacao_transferencia', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_liquidacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_real_liquidacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_envio_cobranca', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_postagem_parcela', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_apolice_seguro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_canal_venda', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_canal_venda', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_recebe_bau', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_serie_bau', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_carne_bau', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ind_serie_pnb_bau', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('tipo_operacao_bau', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nm_local_pagamento_bau', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estabelecimento_lote', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nm_estabelecimento_lote', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('tip_recebimento_lote', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_lote', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_lote', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_seq_lote', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_operador', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_bordero', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('tip_negociacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dat_ano_mes_apuracao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_atualizacao_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_origem_adesao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_forma_pagto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_forma_pagto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_vencimento', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: transacao_contabilizada
transacao_contabilizada_schema = [
    bigquery.SchemaField('id_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_ccred_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_fatura', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_autorizacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_processamento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_processamento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_sequencial_ccred_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_portador_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_estab_transacao_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_estab_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_estab_exter_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_estab_exter_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_contabil_trans', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_contabil_trans', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_gerencial_trans', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_gerencial_trans', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_conta_transacao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_conta_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_origem_transacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_geracao_transacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_transacao', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_vencto_real_transacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_vencto_padrao_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_faturamento_transacao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_vencto_padrao_trans', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_historico_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_evento_exter_trans_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_extrato', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_faturado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_estornado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_estorno', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_complemento_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_funcao_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_geracao_trans', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: transacao_debito
transacao_debito_schema = [
    bigquery.SchemaField('id_conta_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_debito_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_transacao_debito', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_origem_transacao_debito', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_transacao_debito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('nom_tipo_transacao_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_transacao_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_transacao_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_transacao_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_categoria_comerciante', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_categoria_comerciante', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_evento_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_parcela_atual', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('qtde_parcela', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_multiplo', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_multiplo_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_trans_debito', 'DATE', 'NULLABLE'),
]
