from google.cloud import bigquery

# Dataset: pfs_unificacao_pefisa, Table: autorizacao_cartao_credito_hist
autorizacao_cartao_credito_hist_schema = [
    bigquery.SchemaField('id_autorizacao_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_autoriz_ccred', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_funcao_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cartao_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estab_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_estab_autoriz_ccred_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_estab_exter_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_canal_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_canal_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_trans_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_proc_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_transacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_tip_terminal_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tip_terminal_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_band_modo_entrada', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_modo_entrada_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_modo_entrada_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_autorizacao_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('qtd_parcela_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_terml_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_resp_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_status_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_categoria_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_motivo_neg_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_motivo_neg_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_autorizacao_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_autorizacao_ccred_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_nsuhost_autoriz_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tipo_estab_mcc_autoriz', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_estab_mcc_autoriz', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_moeda_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_moeda_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_ccred', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_autoriz_ons', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_instituicao_autoriz_ccred', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_adquirente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_uuid', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_resp_autorizador_antigo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_resp_autorizador_antigo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_autoriz_ccred', 'INTEGER', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: cartao
cartao_schema = [
    bigquery.SchemaField('id_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_via_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_modo_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_atual', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_portador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_bin', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_emis_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_emis_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_embs_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_valid_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_desbloqueio', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_agrp_sit_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_agrp_sit_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estagio_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_estagio_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_estagio_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('flg_embs_loja', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_cancelado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_provisorio', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_debito_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('pt_nomeplastico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ca_arquivolote', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ca_id_imagem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('bc_responsavel', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ca_codigocancelamento', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('ca_flaggeracartasenha', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('pt_id_imagem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_cartao_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_cartao_migrado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_cartao_migrado', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_emis_cartao', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: conta
conta_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('tip_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_ads_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_canal_ads_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_politica', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_mod_score', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_score_aprov_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_operacao_proposta_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_proposta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_colab_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_chapa_colab_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_origem_entrada_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_ori_comercial', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ads_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_ads_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_ads_cred', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_ativacao_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nm_user_ativacao_credito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_agrp_sit_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_agrp_sit_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_financeiro_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_financeiro_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_overall_status_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_overall_status_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_overall_reason_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_overall_reason_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_dia_vencto_fatura', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_alt_vencto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_bloqueada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao_ant', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_grade_produto_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_conta_debito', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_agrp_sit_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_agrp_sit_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_financeiro_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_financeiro_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_overall_status_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_overall_status_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_overall_reason_conta_debito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_overall_reason_conta_debito', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_banco', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_agencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dv_agencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dv_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_debito_bloqueada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_debito_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_adesao_prod_flex', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_cancel_adesao_prod_flex', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_ads_prod_flex', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_adesao_prod_flex', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_cancelamento_prod_flex', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_adesao_carteira_digital_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dt_adesao_carteira_digital', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dt_cancelamento_carteira_digital', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_adesao_carteira_digital', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_cancelamento_carteira_digital', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_overlimit_disp', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_indicacao_amigo_revendedor', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_revendedor', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_indicador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_conta_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_hist_dock', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_migrada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_migracao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_ads_conta', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: conta_hist
conta_hist_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('tip_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_loja_ads_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_canal_ads_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_politica', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_mod_score', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_score_aprov_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_operacao_proposta_so', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_proposta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_colab_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_chapa_colab_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_origem_entrada_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_cliente_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_ori_comercial', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ads_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_ads_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prim_ads_cred', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_sit_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_sit_conta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_sit_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_dia_vencto_fatura', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_prox_vencto_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_alt_vencto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_bloqueada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_cancelada', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao_ant', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_grade_produto_cartao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('cod_banco', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_agencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dv_agencia', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dv_conta_corrente', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_adesao_prod_flex', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_cancel_adesao_prod_flex', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_adesao_carteira_digital_so', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dt_adesao_carteira_digital', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dt_cancelamento_carteira_digital', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_adesao_carteira_digital', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nm_usr_cancelamento_carteira_digital', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_overlimit_disp', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_indicacao_amigo_revendedor', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_conta_revendedor', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_indicador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_ads_conta', 'INTEGER', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: evento_ajuste
evento_ajuste_schema = [
    bigquery.SchemaField('id_evento_ajuste', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_movimento_ajuste', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_tipo_ajuste', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_tipo_ajuste', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_ajuste', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_ajuste', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_origem', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_movimento', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_seq_via_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_funcao_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_vencimento_padrao', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_vencimento_real', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_estabelecimento', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_transacao_original', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_status', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_categoria_autorizacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_responsavel_inclusao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_processamento_lojista', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_borderaux', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_processamento_lojista_dois', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('id_evento_externo_original', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('tip_evento_externo_original', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_lojista', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_estabelecimento_visa', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_destino', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('id_incoming', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_parcela_pedida_incoming', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_origem_resolucao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_debito_conta', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_estabelecimento_externo', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'INTEGER', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: grade_produto
GRADE_PRODUTO_schema = [
    bigquery.SchemaField('id_grade_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_cartao_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_origem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_destino', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_estabelecimento_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_estabelecimento_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_chapa_colaborador_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_colaborador_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_grade_produto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_grade_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_solicitacao_grade_produto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_migracao_grade_produto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_limite_anterior_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_novo_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_origem_web_service', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_responsavel', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_grade_automatico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_mig_grade', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: grade_produto_hist
grade_produto_hist_schema = [
    bigquery.SchemaField('id_grade_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_conta_cartao_credito', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_origem', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_ccred_destino', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_estabelecimento_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_estabelecimento_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_chapa_colaborador_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_colaborador_grade', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_status_grade_produto', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_status_grade_produto', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_solicitacao_grade_produto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_migracao_grade_produto', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('val_limite_anterior_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_novo_ccred', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('flg_origem_web_service', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_responsavel', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('flg_grade_automatico', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_mig_grade', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: limite_disponibilidade
limite_disponibilidade_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_portador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_limite_saque_nac_global', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_global_credito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_saque_nac_global', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_parcela_nac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_global_credito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_parcelas_nac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_maximo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_posicao_limite', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: limite_disponibilidade_hist
limite_disponibilidade_hist_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('cod_tip_portador', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_limite_saque_nac_global', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_global_credito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_saque_nac_global', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_parcela_nac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_disp_global_credito', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_parcelas_nac', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('val_limite_maximo', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_posicao_limite', 'DATE', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: produto_cartao
produto_cartao_schema = [
    bigquery.SchemaField('nom_processadora', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_parceiro', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_produto_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('id_band_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_band_produto_cartao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_bin', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: proposta_credito
proposta_credito_schema = [
    bigquery.SchemaField('id_operacao', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_proposta', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_politica', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_versao_politica', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_resultado_analise', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_instante', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('des_sucesso', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_mensagem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_politica', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_titular', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('des_fase_politica', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('cod_estab_proposta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('nom_consulta_bureau', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_origem_consulta_bureau', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('des_status_consulta_bureau', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dth_relz_consulta_bureau', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('nom_bureau_consultado', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('nom_modelo_score', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('val_score', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_registro', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_proposta_ccred', 'INTEGER', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: saldo_conta
saldo_conta_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_atual_final', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_saldo', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_posicao_saldo', 'DATE', 'NULLABLE'),
]


# Dataset: pfs_unificacao_pefisa, Table: saldo_conta_hist
saldo_conta_hist_schema = [
    bigquery.SchemaField('id_conta', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('id_produto_cartao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('num_cpf_cliente', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('val_saldo_atual_final', 'FLOAT', 'NULLABLE'),
    bigquery.SchemaField('dth_saldo', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('dth_ult_atu_so', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_seq_ult_alteracao', 'INTEGER', 'NULLABLE'),
    bigquery.SchemaField('dth_inclusao_reg', 'TIMESTAMP', 'NULLABLE'),
    bigquery.SchemaField('num_anomes_posicao_saldo', 'DATE', 'NULLABLE'),
    bigquery.SchemaField('des_origem', 'STRING', 'NULLABLE'),
    bigquery.SchemaField('dat_referencia', 'DATE', 'NULLABLE'),
]
